# Frontend on front_vm
- hosts: front_vm
  tasks:
  - name: Copying files for frontend
    become: true
    ansible.builtin.copy:
      src: ./src/frontend/
      dest: /petclinic/frontend/
      
  - name: Building docker image for frontend
    command: docker build -t wus-frontend /petclinic/frontend/
    
  - name: Starting docker container for frontend
    command: docker run -d --name wus-frontend -p {{ frontend_port }}:80 -e API_IP={{ frontend_ip }} -e API_PORT={{ nginx_port }} wus-frontend
    
  - name: Print frontend address and port
    ansible.builtin.debug:
      msg: Frontend available on {{ frontend_ip }}, port {{ frontend_port }}


# Nginx
- hosts: front_vm
  tasks:
  - name: Copying files for nginx
    become: true
    ansible.builtin.copy:
      src: ./src/nginx/
      dest: /petclinic/nginx/
      
  - name: Building docker image for nginx
    command: docker build -t wus-nginx /petclinic/nginx/
    
  - name: Starting docker container for nginx
    command: docker run -d --name wus-nginx -p {{ nginx_port }}:3500 -e BACKEND_IP={{ backend_ip }} -e BACKEND_PORT_1={{ backend_port_1 }} -e BACKEND_PORT_2={{ backend_port_2 }} -e BACKEND_PORT_3={{ backend_port_3 }} wus-nginx
    
  - name: Print nginx address and port
    ansible.builtin.debug:
      msg: Nginx available on {{ frontend_ip }}, port {{ nginx_port }}
      
# Backend_write on back_vm
- hosts: back_vm
  tasks:
  - name: Copying files for backend
    become: true
    ansible.builtin.copy:
      src: ./src/backend/
      dest: /petclinic/backend/
      
  - name: Building docker image for backend
    command: docker build -t wus-backend /petclinic/backend/
    
  - name: Starting docker container for backend 1
    command: docker run -d --name wus-backend-1 -p {{ backend_port_1 }}:3000 -e DB_MASTER_IP={{ db_ip }} -e DB_MASTER_PORT={{ db_port }} wus-backend

  - name: Starting docker container for backend 2
    command: docker run -d --name wus-backend-2 -p {{ backend_port_2 }}:3000 -e DB_MASTER_IP={{ db_ip }} -e DB_MASTER_PORT={{ db_port }} wus-backend
    
  - name: Starting docker container for backend 3
    command: docker run -d --name wus-backend-3 -p {{ backend_port_3 }}:3000 -e DB_MASTER_IP={{ db_ip }} -e DB_MASTER_PORT={{ db_port }} wus-backend

  - name: Print backend address and port
    ansible.builtin.debug:
      msg: Backend available on {{ backend_ip }}, ports - {{ backend_port_1 }}, {{ backend_port_2 }}, {{ backend_port_3 }}
      

# Database on back_vm
- hosts: db_vm
  tasks:
  - name: Copying files for DB
    become: true
    ansible.builtin.copy:
      src: ./src/database/
      dest: /petclinic/db/
      
  - name: Building docker image for DB
    command: docker build -t wus-database /petclinic/db/
    
  - name: Starting docker container for DB
    command: docker run -d --name wus-database -p {{ db_port }}:3306 wus-database
      
  - name: Print database address and port
    ansible.builtin.debug:
      msg: Database available on {{ db_ip }}, port {{ db_port }}
